version: 2
models:

  - name: dim_company
    description: "Dimension table containing stable descriptive attributes of each company."
    columns:

      - name: id
        description: "Primary key assigned to each company"
        tests: ["not_null","unique"]

      - name: symbol
        description: "stock ticker symbol identifying each company in the dataset"

      - name: company_name
        description: "Full legal or trading name of the company."

      - name: cik
        description: "Central Index Key (CIK) assigned by the SEC for unique company identification."

      - name: isin
        description: "International Securities Identification Number identifying the company traded stock."

      - name: cusip
        description: "Committee on Uniform Securities Identification Procedures (CUSIP) number identifying U.S. securities."

      - name: country_code
        description: "Two-letter ISO country code where the company is headquartered."

      - name: industry
        description: "Primary industry category in which the company operates."

      - name: sector
        description: "Broader sector classification of the company (e.g., Technology, Healthcare)."

      - name: reported_currency
        description: "Currency used for reporting financial data (e.g., USD, EUR)."

      - name: exchange_full_name
        description: "Full name of the stock exchange on which the company is listed."

      - name: exchange_code
        description: "Abbreviated exchange identifier (e.g., NASDAQ, NYSE)."

      - name: ceo_name
        description: "Name of the Chief Executive Officer (CEO) of the company."

      - name: website_url
        description: "Official company website URL."

      - name: phone_number
        description: "Company contact phone number."

      - name: address_line
        description: "Street address of the company headquarters."

      - name: city
        description: "City where the company headquarters are located."

      - name: state_code
        description: "State or province code of the company headquarters."

      - name: postal_code
        description: "Postal or ZIP code of the company headquarters."

      - name: full_time_employees
        description: "Number of full-time employees reported by the company."

      - name: ipo_date
        description: "Date on which the company initial public offering (IPO) occurred."

      - name: logo_url
        description: "URL to the company official logo image."

      - name: is_etf
        description: "TRUE if the entity is an Exchange-Traded Fund (ETF); FALSE otherwise."

      - name: is_actively_trading
        description: "TRUE if the company stock is currently active and traded on the exchange."

      - name: is_adr
        description: "TRUE if the company is an American Depositary Receipt (ADR)."
        
      - name: is_fund
        description: "TRUE if the entity represents a fund or investment vehicle rather than a company."

      - name: updated_at
        description: "Timestamp indicating the last refresh of this dimension record."