version: 2

models:
  - name: dim_date
    description: "Date dimension providing calendar and fiscal attributes for time-based analysis."
    columns:

      - name: date_key
        description: "Primiray key in YYYYMMDD integer format."
        tests: ["unique", "not_null"]

      - name: date
        description: "Actual date value."
        tests: ["not_null"]

      - name: month
        description: "Month number (1-12)."
        tests:
          - accepted_values:
              arguments:
                values: [1,2,3,4,5,6,7,8,9,10,11,12]

      - name: year
        description: "Calendar year."

      - name: fiscal_quarter
        description: "Fiscal quarter (1-4)."
        tests:
          - accepted_values:
              arguments:
                values: [1,2,3,4]

      - name: day_of_week
        description: "Day of week number (1=Monday, 7=Sunday)."
        tests:
          - accepted_values:
              arguments:
                values: [1,2,3,4,5,6,7]
              
      - name: is_weekend
        description: "Boolean flag indicating if the day is a weekend."
