"""create raw tabels

Revision ID: 691d2aca7fe8
Revises: 94f4a48ed52a
Create Date: 2025-10-19 14:40:18.527055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '691d2aca7fe8'
down_revision: Union[str, None] = '94f4a48ed52a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('balance_sheet_stmt',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('json_list', sa.JSON(), nullable=False),
    sa.Column('ingestion_ts', sa.TIMESTAMP(), server_default=sa.text("timezone('UTC', now())"), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='raw'
    )
    op.create_table('cash_flow_stmt',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('json_list', sa.JSON(), nullable=False),
    sa.Column('ingestion_ts', sa.TIMESTAMP(), server_default=sa.text("timezone('UTC', now())"), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='raw'
    )
    op.create_table('company_dividends',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('json_list', sa.JSON(), nullable=False),
    sa.Column('ingestion_ts', sa.TIMESTAMP(), server_default=sa.text("timezone('UTC', now())"), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='raw'
    )
    op.create_table('company_profile',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('json_list', sa.JSON(), nullable=False),
    sa.Column('ingestion_ts', sa.TIMESTAMP(), server_default=sa.text("timezone('UTC', now())"), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='raw'
    )
    op.create_table('earnings_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('json_list', sa.JSON(), nullable=False),
    sa.Column('ingestion_ts', sa.TIMESTAMP(), server_default=sa.text("timezone('UTC', now())"), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='raw'
    )
    op.create_table('income_stmt',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('json_list', sa.JSON(), nullable=False),
    sa.Column('ingestion_ts', sa.TIMESTAMP(), server_default=sa.text("timezone('UTC', now())"), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='raw'
    )
    op.create_table('price_changes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('json_list', sa.JSON(), nullable=False),
    sa.Column('ingestion_ts', sa.TIMESTAMP(), server_default=sa.text("timezone('UTC', now())"), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='raw'
    )
    op.create_table('shares_float',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('json_list', sa.JSON(), nullable=False),
    sa.Column('ingestion_ts', sa.TIMESTAMP(), server_default=sa.text("timezone('UTC', now())"), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='raw'
    )
    op.create_table('stock_quotes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('json_list', sa.JSON(), nullable=False),
    sa.Column('ingestion_ts', sa.TIMESTAMP(), server_default=sa.text("timezone('UTC', now())"), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='raw'
    )
    op.create_table('stock_splits',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('json_list', sa.JSON(), nullable=False),
    sa.Column('ingestion_ts', sa.TIMESTAMP(), server_default=sa.text("timezone('UTC', now())"), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='raw'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock_splits', schema='raw')
    op.drop_table('stock_quotes', schema='raw')
    op.drop_table('shares_float', schema='raw')
    op.drop_table('price_changes', schema='raw')
    op.drop_table('income_stmt', schema='raw')
    op.drop_table('earnings_reports', schema='raw')
    op.drop_table('company_profile', schema='raw')
    op.drop_table('company_dividends', schema='raw')
    op.drop_table('cash_flow_stmt', schema='raw')
    op.drop_table('balance_sheet_stmt', schema='raw')
    # ### end Alembic commands ###
