"""create company_id_map in marts schema

Revision ID: 6c77d0a8cec7
Revises: 691d2aca7fe8
Create Date: 2025-10-19 15:18:25.960487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c77d0a8cec7'
down_revision: Union[str, None] = '691d2aca7fe8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_id_map',
    sa.Column('company_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text("timezone('UTC', now())"), nullable=True),
    sa.PrimaryKeyConstraint('company_id'),
    sa.UniqueConstraint('symbol'),
    schema='marts'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('company_id_map', schema='marts')
    # ### end Alembic commands ###
