"""Add source column to raw schema tables

Revision ID: 8973bc216e38
Revises: 6c77d0a8cec7
Create Date: 2025-10-21 21:44:23.284037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8973bc216e38'
down_revision: Union[str, None] = '691d2aca7fe8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('balance_sheet_stmt', sa.Column('source', sa.String(length=100), nullable=False), schema='raw')
    op.add_column('cash_flow_stmt', sa.Column('source', sa.String(length=100), nullable=False), schema='raw')
    op.add_column('company_dividends', sa.Column('source', sa.String(length=100), nullable=False), schema='raw')
    op.add_column('company_profile', sa.Column('source', sa.String(length=100), nullable=False), schema='raw')
    op.add_column('earnings_reports', sa.Column('source', sa.String(length=100), nullable=False), schema='raw')
    op.add_column('income_stmt', sa.Column('source', sa.String(length=100), nullable=False), schema='raw')
    op.add_column('price_changes', sa.Column('source', sa.String(length=100), nullable=False), schema='raw')
    op.add_column('shares_float', sa.Column('source', sa.String(length=100), nullable=False), schema='raw')
    op.add_column('stock_quotes', sa.Column('source', sa.String(length=100), nullable=False), schema='raw')
    op.add_column('stock_splits', sa.Column('source', sa.String(length=100), nullable=False), schema='raw')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock_splits', 'source', schema='raw')
    op.drop_column('stock_quotes', 'source', schema='raw')
    op.drop_column('shares_float', 'source', schema='raw')
    op.drop_column('price_changes', 'source', schema='raw')
    op.drop_column('income_stmt', 'source', schema='raw')
    op.drop_column('earnings_reports', 'source', schema='raw')
    op.drop_column('company_profile', 'source', schema='raw')
    op.drop_column('company_dividends', 'source', schema='raw')
    op.drop_column('cash_flow_stmt', 'source', schema='raw')
    op.drop_column('balance_sheet_stmt', 'source', schema='raw')
    # ### end Alembic commands ###
