version: 2

models:
  - name: stg_dim_date
    description: "Date dimension providing calendar and fiscal attributes for time-based analysis."
    columns:
      - name: date_key
        description: "Surrogate key in YYYYMMDD integer format."
        tests: ["unique", "not_null"]
      - name: date
        description: "Actual date value."
        tests: ["not_null"]
      - name: month
        description: "Month number (1-12)."
      - name: year
        description: "Calendar year."
      - name: fiscal_quarter
        description: "Fiscal quarter (1-4)."
      - name: day_of_week
        description: "Day of week number (1=Monday, 7=Sunday)."
      - name: is_weekend
        description: "Boolean flag indicating if the day is a weekend."

  - name: company_id_map
    description: "Mapping table assigning a persistent unique company_id to each unique stock symbol. 
      The table is incremental to ensure stable identifiers across refreshes."
    columns:
      - name: company_id
        description: "Persistent unique key assigned to each unique symbol."
        tests:
          - not_null
          - unique

      - name: symbol
        description: "Unique stock or company symbol serving as the natural key for identification."
        tests:
          - not_null
          - unique

      - name: created_at
        description: "Timestamp indicating when the mapping record was created."
