version: 2

models:

  - name: stg_dim_date
    description: "Structural contract for date dimension staging model."
    columns:
      - name: date_key
        data_type: integer
      - name: date
        data_type: date
      - name: month
        data_type: integer
      - name: year
        data_type: integer
      - name: quarter
        data_type: integer
      - name: day_of_week
        data_type: integer
      - name: is_weekend
        data_type: boolean


  - name: company_id_map
    description: "Structural contract for persistent company ID mapping model (symbol - company_id)."
    columns:
      - name: company_id
        data_type: integer
      - name: symbol
        data_type: varchar
      - name: created_at
        data_type: timestamptz
